# Generated by Django 4.1.2 on 2023-01-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0003_alter_events_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='repeatable',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='NO', max_length=3),
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.CharField(blank=True, choices=[('General', 'General'), ('Children’s Ministries', 'Children’s Ministries'), ('Communication Department', 'Communication Department'), ('Family Ministries', 'Family Ministries'), ('Health Ministries Department', 'Health Ministries Department'), ('Sabbath School', 'Sabbath School'), ('Small Group Ministry', 'Small Group Ministry'), ('Women’s Ministries', 'Women’s Ministries'), ('Youth Department', 'Youth Department'), ('Pathfinder Club', 'Pathfinder Club'), ('Adventurers Club', 'Adventurers Club'), ('Music Ministry', 'Music Ministry'), ('Church Treasure', 'Church Treasure'), ('Deacon Ministry', 'Deacon Ministry')], default='', max_length=100),
        ),
    ]
