# Generated by Django 4.1.2 on 2023-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0006_events_end_date_events_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
