# Generated by Django 4.1.2 on 2023-01-12 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0009_alter_events_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('description', models.CharField(max_length=10000, null=True)),
                ('leader', models.CharField(blank=True, max_length=100, null=True)),
                ('leader_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=50)),
                ('slug', models.SlugField(blank=True, default='')),
            ],
        ),
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='tisdac_app.department'),
        ),
    ]
