# Generated by Django 4.1.2 on 2023-01-12 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0010_department_alter_events_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tisdac_app.department'),
        ),
    ]
