# Generated by Django 4.1.2 on 2023-01-17 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0014_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='annotation',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
