# Generated by Django 4.1.2 on 2023-01-18 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0016_visitor_rename_annotation_service_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='visitors',
            field=models.ManyToManyField(to='tisdac_app.visitor'),
        ),
    ]
