# Generated by Django 4.1.2 on 2023-01-18 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0017_events_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
