# Generated by Django 4.1.2 on 2023-01-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0018_alter_visitor_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='visitors_marker',
            field=models.BooleanField(blank=True, default=True, max_length=6),
        ),
    ]
