# Generated by Django 4.1.2 on 2023-01-19 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0021_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='publish',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='YES', max_length=3),
        ),
    ]
