# Generated by Django 4.1.2 on 2023-01-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0024_alter_events_visitors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='visitors',
            field=models.ManyToManyField(blank=True, to='tisdac_app.visitor'),
        ),
    ]
