# Generated by Django 4.1.2 on 2023-01-19 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0025_alter_news_visitors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='visitors_marker',
        ),
    ]
