# Generated by Django 4.1.2 on 2023-01-23 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0026_remove_events_visitors_marker'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='about'),
        ),
        migrations.AddField(
            model_name='department',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='department'),
        ),
        migrations.AddField(
            model_name='events',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='event'),
        ),
        migrations.AddField(
            model_name='news',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='news'),
        ),
        migrations.AddField(
            model_name='service',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
    ]
