# Generated by Django 4.1.2 on 2023-01-23 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0027_about_image_department_image_events_image_news_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='department',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='events',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='events',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='news',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='news',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='image2',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
        migrations.AddField(
            model_name='service',
            name='image3',
            field=models.FileField(blank=True, null=True, upload_to='service'),
        ),
    ]
