# Generated by Django 4.1.2 on 2023-01-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0028_department_image2_department_image3_events_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='image',
            field=models.FileField(null=True, upload_to='department'),
        ),
    ]
