# Generated by Django 4.1.2 on 2023-01-23 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0031_news_video_youtube_link_alter_news_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image2',
            new_name='image_2',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image3',
            new_name='image_3',
        ),
    ]
