# Generated by Django 4.1.2 on 2023-01-23 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0032_rename_image2_news_image_2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='news',
            old_name='image_2',
            new_name='image2',
        ),
        migrations.RenameField(
            model_name='news',
            old_name='image_3',
            new_name='image3',
        ),
    ]
