# Generated by Django 4.1.2 on 2023-01-23 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0033_rename_image_2_news_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='article',
            field=models.TextField(default=''),
        ),
    ]
