# Generated by Django 4.1.2 on 2023-01-25 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0039_feedback_date_alter_feedback_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('summary', models.CharField(max_length=100, null=True)),
                ('description', models.TextField(null=True)),
                ('logo', models.FileField(null=True, upload_to='resource')),
                ('webpage', models.CharField(max_length=1500, null=True)),
            ],
        ),
    ]
