# Generated by Django 4.1.2 on 2023-01-27 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tisdac_app', '0040_resource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='publish',
            field=models.CharField(choices=[('YES', 'YES'), ('NO', 'NO'), ('ONLY FOR REGISTERED', 'FOR REGISTERED')], default='YES', max_length=19),
        ),
    ]
